config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :shopping_cart
      post :create_order_old_info
      post :remove_product_cart_from_cart
    end
  end
  get 'cart/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'contact' => 'contact#index'
  get 'about' => 'about#index'
  root to: 'home#index'

  resources :products do
    member do
      post :add_to_cart
      post :add_to_wishlist
      post :quick_view
      post :update_form_add_to_cart
    end

    collection do
      post :save_attributes
      post :create_variations_from_attrs
      post :change_product_form
      post :add_attributes_input
      post :filter_by_price
      post :add_comment
      post :add_reply
      post :show_replies
      post :add_reply_form
      post :toggle_like
      post :add_category
    end
  end
  resources :user do
  end
  resources :comment
  resources :user, collection: {add_to_cart: :post}

  resources :cart do
    collection do
      post :modify_qty
      post :view_cart
    end
  end
  devise_for :users do
    get '/users/sign_out' => 'devise/session#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :product_carts, as: :product_cart_container

  def total
    ret = 0
    product_carts.each do |item|
      ret += (item.product.price || 0) * item.quantity
    end
    ret
  end

  def subtotal
    ret = 0
    product_carts.each do |item|
      ret += (item.product.price || 0) * item.quantity
    end
    ret
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @cart = Cart.find_by(user_id: current_user.id)
    @order_view = OrderNewView.new(@cart, view_context)
  end

  def view_cart
    @cart_view = CartView.new(current_user)
    respond_to do |format|
      format.js { render 'cart/show_cart_popup' }
    end
  end

  def modify_qty
    print(params)
    qty = params['qty']
    id = params['product-cart-id']
    @product_cart = ProductCart.find(id)
    @product_cart.quantity = qty
    respond_to do |format|
      if @product_cart.save
        format.js { render 'cart/response_modify_qty', locals: { success: true } }
      else
        format.js { render 'cart/response_modify_qty', locals: { success: false } }
      end
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart_popup.html.erb
<% if cart.product_carts.blank? %>
  <section class="rounded-md cart-popup bg-white shadow-md mx-auto py-3">
    <h6 class="text-center font-baloo font-bold f4 m-0 p-0">NO ITEMS IN CART</h6>
  </section>
<% else %>
  <section class="rounded-md cart-popup bg-white shadow-md mx-auto py-3">
    <div id="cart-popup-items">
      <% cart.product_carts.each do |product_cart| %>
        <div class="flex mx-3 p-0 my-1 shadow-md flex-grow rounded-md justify-between pr-3">
          <div class="flex">
            <div>
              <%= image_tag(product_first_img(product_cart.product), width: 64, height: 64) %>
            </div>
            <div class="ml-3 flex flex-col justify-center">
              <p class="my-0"><%= product_cart.product.name %></p>
              <p class="fw6 f6">
                <span class="text-gray-600 opacity-50"> <%= product_cart.quantity > 1 ? "#{product_cart.quantity} x " : "" %></span><%= number_to_currency(product_cart.product.price) %>
              </p>
            </div>
          </div>
          <div class="flex items-center cursor-pointer">
            <i class="fa fa-times-circle fa-lg"></i>
          </div>
        </div>
      <% end %>
    </div>
    <h6 class="text-center mt-3 font-baloo font-bold f4">Subtotal:
      <span id="cart-popup-subtotal" class="font-baloo font-bold f3"><%= cart.subtotal %></span></h6>
    <div class="button-wishlist text-center flex justify-center mx-6 my-3">
      <%= link_to shopping_cart_orders_path, class: "link-no-style" do %>
        <button class="flex font-roboto f6 outline-none-imp font-bold items-center duration-500">
          <i class="fa fa-shopping-cart mr-3 duration-500"></i>VIEW CART
        </button>
      <% end %>

    </div>
    <div class="button-wishlist flex justify-center mx-6 my-3">
      <%= link_to new_order_path, class: "link-no-style" do %>
        <button type="submit" class="flex font-roboto f6 outline-none-imp font-bold items-center duration-500">
          <i class="fa fa-heart mr-3 duration-500"></i>CHECK OUT
        </button>
      <% end %>
    </div>

  </section>
<% end %>

app/views/cart/index.html.erb
<%#= form %>

<section class="w-9/12 mx-auto mt-5">
  <div class="text-center flex justify-center">
    <h3>SHOPPING CART <span class="text-gray-500">> CHECKOUT > BUY</span></h3>
  </div>
  <div class="flex mt-4 border py-3">
    <div class="w-8/12">
      <div class="flex">
        <div class="w-6/12 font-bold text-gray-800 f6">PRODUCT</div>
        <div class="w-1/12 font-bold text-gray-800 f6">PRICE</div>
        <div class="w-2/12 font-bold text-gray-800 f6 p-0">QUANTITY</div>
        <div class="w-2/12 font-bold text-gray-800 f6 text-right">SUBTOTAL</div>
      </div>
      <hr>
      <div class="flex justify-center items-center">
        <div class="w-6/12 font-bold f6 flex items-center">
          <i class="fa fa-times-circle fa-lg"></i>
          <%= image_tag("product_6.jpg", class: " img-avatar ml-3") %>
          <h6 class="ml-3 text-gray-800">Iphone</h6>
        </div>
        <div class="w-2/12 font-bold f6 text-gray-800">$500</div>
        <div class="w-2/12 font-bold f6 p-0">
          <div class="flex text-center mt-2">
            <button type="button" class="qty-up px-2 border bg-light">
              <i class="fas fa-angle-up" data-id="prod1"></i>
            </button>
            <input type="number" name="quantity" id="quantity" class="qty-input w-1/4 text-center border px-2 bg-light"
                   readonly="readonly"
                   value="1" placeholder="1" data-id="prod1">
            <button type="button" class="qty-down px-2 border bg-light" data-id="prod1">
              <i class="fas fa-angle-down"></i>
            </button>
          </div>
        </div>
        <div class="w-2/12 font-bold f6 text-gray-800 text-right">$500</div>
      </div>

      <hr>
      <div class="flex justify-center items-center">
        <div class="w-6/12 font-bold f6 flex items-center">
          <i class="fa fa-times-circle fa-lg"></i>
          <%= image_tag("product-10-300x330.jpg", class: " img-avatar ml-3") %>
          <h6 class="ml-3 text-gray-800">Ecommer Phone</h6>
        </div>
        <div class="w-2/12 font-bold f6 text-gray-800">$300</div>
        <div class="w-2/12 font-bold f6 p-0">
          <div class="flex text-center mt-2">
            <button type="button" class="qty-up px-2 border bg-light">
              <i class="fas fa-angle-up" data-id="prod1"></i>
            </button>
            <input type="number" name="quantity" id="quantity" class="qty-input w-1/4 text-center border px-2 bg-light"
                   readonly="readonly"
                   value="1" placeholder="1" data-id="prod1">
            <button type="button" class="qty-down px-2 border bg-light" data-id="prod1">
              <i class="fas fa-angle-down"></i>
            </button>
          </div>
        </div>
        <div class="w-2/12 font-bold f6 text-gray-800 text-right">$300</div>
      </div>


      <div class="flex mt-3">
        <div class="button-wishlist inline-block">
          <button type="submit" class="flex font-roboto f6 outline-none-imp font-bold items-center duration-500">
            <i class="fa fa-arrow-left mr-3 duration-500"></i>CONTINUE SHOPPING
          </button>
        </div>
        <div class="button-wishlist inline-block ml-5">
          <button type="submit" class="flex font-roboto f6 outline-none-imp font-bold items-center duration-500">
            <i class="fa fa-shopping-cart mr-3 duration-500"></i>UPDATE CART
          </button>
        </div>
      </div>

    </div>
    <div class="w-4/12">
      <div class="font-bold text-gray-800 f6">CART TOTALS</div>
      <hr>
      <div class="flex justify-between items-center">
        <span class="text-gray-600 f6">Subtotal</span>
        <span class="font-bold f5">$500</span>
      </div>
      <div class="flex justify-between items-center mt-2">
        <span class="text-gray-600 f6">Total</span>
        <span class="font-bold f5">$500</span>
      </div>
      <hr class="mt-2">
      <div class="flex justify-center button-wishlist inline-block">
        <button type="submit" class="flex font-roboto f6 outline-none-imp font-bold items-center duration-500">
          <i class="fa fa-heart mr-3 duration-500"></i>PROCESS TO CHECKOUT
        </button>
      </div>
      <hr class="my-3">

      <div>
        <div class="flex items-center mt-2">
          <i class="fa fa-tags"></i>
          <span class="ml-2 font-bold f5">Coupon</span>
        </div>
        <div class="field">
          <div class="control flex mt-2 justify-start">
            <input placeholder="Coupon Code" type="text" class="input w-full flex-grow w-full py-2 rounded-lg font-medium bg placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white placeholder-gray-800">
          </div>
        </div>
      </div>

      <hr class="my-2">
      <div class="flex justify-center button-wishlist inline-block">
        <button type="submit" class="flex font-roboto f6 outline-none-imp font-bold items-center duration-500">
          <i class="fa fa-tag mr-3 duration-500"></i>Use Coupon
        </button>
      </div>
    </div>
  </div>
</section>

app/views/cart/response_modify_qty.js.erb
<% if success %>
$("#product-total-<%= @product_cart.id %>").text("<%= number_to_currency(@product_cart.product.price * @product_cart.quantity) %>")
$("#cart-total").text("<%= number_to_currency(@product_cart.product_cart_container.total) %>")
$("#cart-subtotal").text("<%= number_to_currency(@product_cart.product_cart_container.total) %>")
<% else %>
toastr.error("Something went wrong!")
<% end %>

app/views/cart/show_cart_popup.js.erb
//$("#cart-items")?.text("<%#= @cart_view.cart_items %>")

//$("#cart-popup-items").html("<%#= escape_javascript render 'cart/cart_popup_item', product_carts: @cart_view.product_carts %>")
//$("#cart-popup-container")

var popupContainer = $("#cart-popup-container")
popupContainer.html("<%= escape_javascript render 'cart/cart_popup', cart: @cart_view %>")
popupContainer.css('display', 'initial').css('opacity', '1')
$("#cart-popup-subtotal").text("<%= number_to_currency(@cart_view.subtotal) %>")

var timerFadeOut = timerFadeOut ?? setTimeout(() => {
    $("#cart-popup-container").css('opacity', '0')

}, 3000)

var timerRemove = timerRemove ?? setTimeout(() => {
    $("#cart-popup-container").css('display', 'none')
}, 6000)


popupContainer.mouseenter(function () {
    clearTimeout(timerFadeOut)
    clearTimeout(timerRemove)
})

popupContainer.mouseleave(function () {
    timerFadeOut = setTimeout(() => {
        $("#cart-popup-container").css('opacity', '0')

    }, 3000)

    timerRemove = setTimeout(() => {
        $("#cart-popup-container").css('display', 'none')
    }, 6000)

    popupContainer.mouseenter(function () {
        clearTimeout(timerFadeOut)
        clearTimeout(timerRemove)
    })
})