config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :shopping_cart
      post :create_order_old_info
      post :remove_product_cart_from_cart
    end
  end
  get 'cart/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'contact' => 'contact#index'
  get 'about' => 'about#index'
  root to: 'home#index'

  resources :products do
    member do
      post :add_to_cart
      post :add_to_wishlist
      post :quick_view
      post :update_form_add_to_cart
    end

    collection do
      post :save_attributes
      post :create_variations_from_attrs
      post :change_product_form
      post :add_attributes_input
      post :filter_by_price
      post :add_comment
      post :add_reply
      post :show_replies
      post :add_reply_form
      post :toggle_like
      post :add_category
    end
  end
  resources :user do
  end
  resources :comment
  resources :user, collection: {add_to_cart: :post}

  resources :cart do
    collection do
      post :modify_qty
      post :view_cart
    end
  end
  devise_for :users do
    get '/users/sign_out' => 'devise/session#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="background-light text-semi-white">

  <div class="flex mx-5 py-4 child-pr-2-not-first w-9/12 mx-auto">

    <div class="w-3/12">
      <div class="break-bottom mt-4">
        <div>
          <%= image_tag("svg/logo.svg", class: "w-16 h-16") %>
        </div>
        <h6 class="f6 mt-2 font-elia text-blue-500 uppercase font-bold break-bottom">Ecommer</h6>
      </div>
      <div class="my-8">
        <p class="text-gray-800 f7">ECOMMER - worldwide online shop</p>
        <p class="text-gray-800 f7">We sell over 1000+ branded products</p>
      </div>
    </div>

    <div class="w-2/12">
      <div class="break-bottom mt-4">
        <h6 class="f6 font-josesans text-gray-900 uppercase font-bold break-bottom">Information</h6>
      </div>
      <div class="mt-8">
        <p class="text-gray-800 f7 my-4">New collection</p>
        <p class="text-gray-800 f7 my-4">About Store</p>
        <p class="text-gray-800 f7 my-4">Contact Us</p>
        <p class="text-gray-800 f7 my-4">Latest News</p>
        <p class="text-gray-800 f7 my-4">Our Sitemap</p>
        <p class="text-gray-800 f7 my-4">Order history</p>
      </div>
    </div>

    <div class="w-2/12">
      <div class="break-bottom mt-4">
        <h6 class="f6 font-josesans text-gray-900 uppercase font-bold break-bottom">Footer menu</h6>
      </div>
      <div class="mt-8">
        <p class="text-gray-800 f7 my-4">Instagram Profile</p>
        <p class="text-gray-800 f7 my-4">New Collection</p>
        <p class="text-gray-800 f7 my-4">Call Us</p>
        <p class="text-gray-800 f7 my-4">Latest Stories</p>
        <p class="text-gray-800 f7 my-4">Terms & Conditions</p>
        <p class="text-gray-800 f7 my-4">Purchase Products</p>
      </div>
    </div>

    <div class="w-2/12">
      <div class="break-bottom mt-4">
        <h6 class="f6 font-josesans text-gray-900 uppercase font-bold break-bottom">Shortcut Link</h6>
      </div>
      <div class="mt-8">
        <p class="text-gray-800 f7 my-4">Facebook Profile</p>
        <p class="text-gray-800 f7 my-4">New Product</p>
        <p class="text-gray-800 f7 my-4">Talk Us</p>
        <p class="text-gray-800 f7 my-4">Latest Products</p>
        <p class="text-gray-800 f7 my-4">Privacy Policy</p>
        <p class="text-gray-800 f7 my-4">Sell Products</p>
      </div>
    </div>

    <div class="w-3/12">
      <div class="break-bottom mt-4">
        <h6 class="f6 font-josesans text-gray-900 uppercase font-bold break-bottom">About Ecommer</h6>
      </div>
      <div class="my-8">
        <p class="text-gray-800 f7">ECOMMER - worldwide online shop</p>
        <p class="text-gray-800 f7">We sell over 1000+ branded products</p>
      </div>

      <p class="f7 my-4 text-gray-900">www.company.com</p>
      <div class="flex child-mx-2-not-first text-gray-900">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-twitter"></i>
        <i class="fab fa-linkedin-in"></i>
        <i class="fab fa-youtube"></i>
      </div>
    </div>
  </div>

</footer>

app/views/shared/_header.html.erb
<%= render 'shared/nav' %>
<div class="heading-banner justify-between items-center flex">
  <div class="text-left my-auto ml-16 w-50">
    <h5 class="f5 font-bold text-gray-900">SPACE JUST GOT PERSONAL</h5>
    <h1 class="f1 font-josesans font-bold text-gray-900">The New iPhone Watch</h1>
    <p class="f6 text-gray-800">High quality iPhone Watch to meet your need!</p>
    <h3>$1238</h3>

    <div class="flex mx-0 mt-4">
      <div class="btn btn-lg-outline opacity-anim translate-y-anim background-dark text-white cursor-pointer fw6">Buy now</div>
      <div class="btn ml-4 btn-lg-outline text-dark bg-light fw6 px-5 cursor-pointer">More info</div>
    </div>
  </div>

  <div class="w-3/12 mr-32">
    <%= image_tag("black-apple-watch.png") %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar w-full navbar-expand-lg flex items-center relative py-2 px-4 border-b">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="w-4/12 justify-start flex">
    <div class="mr-4">
      <%= image_tag("svg/logo.svg", class: "w-8 h-8") %>
    </div>
    <h3 class="uppercase font-elia text-blue-500 text-center font-bold f4 m-0">Ecommer</h3>
  </div>
  <div class="collapse navbar-collapse md:flex" id="navbarSupportedContent">
    <ul class="flex w-1/2 m-0 list-unstyled text-gray-900">
      <li>
        <%= link_to "Home", root_path, class: "f5 font-bold font-josesans text-gray-900" %>
      </li>
      <li>
        <% if current_user %>
          <%= link_to "Account", user_path(current_user), class: "f5 font-bold font-josesans text-gray-900" %>
        <% else %>
          <%= link_to "Signup", new_user_registration_path, class: "f5 font-bold font-josesans text-gray-900" %>
        <% end %>
      </li>
      <li>
        <%= link_to "Shop", products_path, class: "f5 font-bold font-josesans text-gray-900" %>
      </li>
      <li>
        <%= link_to "Product", new_product_path, class: "f5 font-bold font-josesans text-gray-900" %>
      </li>
      <li>
        <%= link_to "About", about_path, class: "f5 font-bold font-josesans text-gray-900" %>
      </li>
      <li>
        <%= link_to "Contact", contact_path, class: "f5 font-bold font-josesans text-gray-900" %>
      </li>
    </ul>
  </div>

  <div class="md:w-4/12 sm:w-5/12">
    <div class="flex justify-end items-center">
      <div class="flex items-center mr-4">
        <% if current_user %>
          <h6 class="text-gray-800 f6 font-josesans m-0 mr-3 flex justify-center flex-col"><%= current_user.username %></h6>
          <%= image_tag("portrait-3204843_640.jpg", class: "rounded-circle img-avatar-small") %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "f5 font-bold" %>
          </li>
        <% end %>
      </div>
      <div class="flex m-0">
        <div class="flex font-roboto outline-none-imp font-bold items-center duration-500">
          <i class="fa fa-lg fa-shopping-cart text-gray-800 mr-3 duration-500">&nbsp;/</i>
          <button type="submit" class="inline-block text-gray-800 cart-items" id="cart-items">
            <%= cart_items %>
          </button>
        </div>
      </div>
      <!--      Cart Popup-->
      <div id="cart-popup-container" class="absolute w-1/4 top-0 shadow-2xl rounded-md z-40 mt-12">
      </div>
      <!--       !Cart Popup-->

    </div>

  </div>


</nav>

app/views/shared/_new_letter.html.erb
<section class="w-full mbr new-letter py-5 px-5">
  <div class="flex my-2 h-100">
    <div class="w-4/12">
      <%= image_tag("newsletter.jpg", class: "h-100 object-covert") %>
    </div>
    <div class="container w-50 py-3">
      <h3 class="font-fredoka">NewLetter</h3>
      <p class="f6">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor error modi nisi quasi rerum
        similique velit voluptates. Cum harum id, magnam nostrum officiis quaerat quasi quidem ratione saepe suscipit
        voluptate!</p>
      <div class="mt-2">
        <label for="email">Your Email</label>
        <input class="w-full" name="email" type="email">
        <button class="my-3 btn background-black px-5 text-white py-2 font-bold">Submit</button>
      </div>

    </div>
  </div>
</section>

app/views/shared/_product_cart.html.erb
<div class="card">
  <%= image_tag("product 1.jpg", alt: "Product", class: "card-img-top") %>
  <div class="card-body">
    <h5 class="card-title">Product Title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <div class="rating text-warning font-size-14">
      <span><i class="fas fa-star"></i></span>
      <span><i class="fas fa-star"></i></span>
      <span><i class="fas fa-star"></i></span>
      <span><i class="fas fa-star"></i></span>
      <span><i class="fas fa-star"></i></span>
    </div>
    <p>$300.00</p>
    <button class="btn">Add To Cart</button>
  </div>
</div>

app/views/shared/_product_extra.html.erb
<!-- General Attr Tab -->
<div id="general-product-attr">
  <div class="field mt-5">
    <div class="control">
      <%= f.input :regular_price, label: "Regular price ($)", required: false,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :sale_price, label: "Sale price ($)", required: false,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>
</div>
<!-- !General Attr Tab -->

<!-- Inventory Attr Tab -->
<div id="inventory-product-attr">
  <div class="field mt-5">
    <div class="control">
      <%= f.input :sku, label: "SKU", required: true,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :manage_stock, label: "Manage Stock?", required: false,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :sale_price, label: "Sale price ($)", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>
</div>
<!-- !Inventory Attr Tab -->

<!-- Shipping Attr Tab -->
<div id="shipping-product-attr">
  <div class="field mt-5">
    <div class="control">
      <%= f.input :weight, label: "Weights (kg)", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>
  <div class="columns">
    <div class="field mt-5 w-4/12">
      <div class="control">
        <%= f.input :manage_stock, label: "Length", required: false,
                    input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
      </div>
    </div>

    <div class="field mt-5 w-4/12">
      <div class="control">
        <%= f.input :manage_stock, label: "Width", required: false,
                    input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
      </div>
    </div>

    <div class="field mt-5 w-4/12">
      <div class="control">
        <%= f.input :manage_stock, label: "Height", required: false,
                    input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
      </div>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :shipping_class, label: "Shipping Class", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>
</div>
</div>
<!-- !Shipping Attr Tab -->

<!-- Link Product Tab -->
<div id="link-product-attr">
  <div class="field mt-5">
    <div class="control">
      <%= f.input :upsells, label: "Upsells", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :cross_sells, label: "Cross sells", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>
</div>
<!-- !Link Product Tab -->

<!-- Advanced Product Tab -->
<div id="advanced-product-attr">
  <div class="field mt-5">
    <div class="control">
      <%= f.input :purchase_note, label: "Purchase note", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :menu_order, label: "Menu order", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>
</div>
<!-- !Advanced Product Tab -->

<!-- Extra Product Tab -->
<div id="extra-product-attr">
  <div class="field mt-5">
    <div class="control">
      <%= f.input :custom_bubbles, label: "Custom Bubble", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :custom_bubbles_title, label: "Custom Bubbles Title", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :custom_tab_title, label: "Custom Tab Title", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>

  <div class="field mt-5">
    <div class="control">
      <%= f.input :custom_tab_content, label: "Custom Tab Content", required: false ,
                  input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
    </div>
  </div>
</div>

<div class="field mt-5">
  <div class="control">
    <%= f.input :product_video_path, label: "Product Video Url", required: false ,
                input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
  </div>
</div>

<div class="field mt-5">
  <div class="control">
    <%= f.input :top_content, label: "Custom Tab Title", required: false ,
                input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
  </div>
</div>

<div class="field mt-5">
  <div class="control">
    <%= f.input :bottom_contetn, label: "Custom Tab Title", required: false ,
                input_html: {class: "input w-full"}, wrapper: false, label_html: {class: "label text-left w-full"} %>
  </div>
</div>
<!-- !Extra Product Tab -->