config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :shopping_cart
      post :create_order_old_info
      post :remove_product_cart_from_cart
    end
  end
  get 'cart/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'contact' => 'contact#index'
  get 'about' => 'about#index'
  root to: 'home#index'

  resources :products do
    member do
      post :add_to_cart
      post :add_to_wishlist
      post :quick_view
      post :update_form_add_to_cart
    end

    collection do
      post :save_attributes
      post :create_variations_from_attrs
      post :change_product_form
      post :add_attributes_input
      post :filter_by_price
      post :add_comment
      post :add_reply
      post :show_replies
      post :add_reply_form
      post :toggle_like
      post :add_category
    end
  end
  resources :user do
  end
  resources :comment
  resources :user, collection: {add_to_cart: :post}

  resources :cart do
    collection do
      post :modify_qty
      post :view_cart
    end
  end
  devise_for :users do
    get '/users/sign_out' => 'devise/session#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @products_view = Product
                     .all
                     .map { |product| ProductView.new(product) }
    @products_view_sale = Product
                          .joins(product_meta: [:product_sale_price])
                          .where('sale_date_start < ?', 0.day.ago)
                          .map { |product| ProductView.new(product) }
    @cart_items = ProductCart.count
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- Service -->

<section class="mx-auto my-3 font-weight-lighter w-11/12">
  <h1 class="font-josesans f1 text-center font-bold mt-8 f1">Our features</h1>
  <p class="w-8/12 mx-auto text-center">Special product created just for you. We aim to provide memorable experience
    when you shop on our
    online store by offering quality products with top rated customer service</p>
  <div class="flex mx-auto mt-12 child-mx-2-not-first">
    <div class="w-4/12 text-center">
      <i class="fas fa-dolly fa-3x"></i>
      <div class="h5 my-3 f3 font-josesans">Priority Shipping</div>
      <div class="">Shipping in hours for flash ship products. Free ship for large orders</div>
    </div>

    <div class="w-4/12 text-center">
      <i class="fas fa-balance-scale fa-3x"></i>
      <div class="h5 my-3 f3 font-josesans">Fuss Free Returns</div>
      <div class="">Check products before pay. Free return fee if products have errors</div>
    </div>
    <div class="w-4/12 text-center">
      <i class="fas fa-user-cog fa-3x"></i>
      <div class="h5 my-3 f3 font-josesans">In Home Setup</div>
      <div class="">Shipping in home and guide</div>
    </div>

  </div>
  <!-- Service -->
  <div class="flex text-white mbr mx-auto border-dark p-0 my-0 child-mx-2-not-first">
    <div class="lg:w-5/12 sm:w-full my-3 cursor-pointer relative">
      <div class="h-full img-container">
        <%= image_tag("Image-28.jpg", alt: "Hero 1", class: "img-banner h-100") %>
      </div>
      <div class="center-inner z-10 text-white w-full">
        <h5>Watches</h5>
        <h5 class="mt-4 font-bold font-josesans">50% OFF TODAY</h5>
        <%= link_to products_url do %>
          <div class="absolute rounded-circle ml-auto mr-8 w-24 h-24 bg-black mt-4 flex flex-col justify-center items-center">
            <span class="material-icons text-white">north_east</span>
            <p class="text-white h6 font-josesans mt-2">Shop now</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="lg:w-4/12 sm:w-full my-3 p-0 cursor-pointer relative">
      <div class="h-full img-container">
        <%= image_tag("blog post 3.jpg", alt: "Hero 1", class: "img-banner h-100") %>
      </div>
      <div class="center-inner z-10 text-white w-full px-2">
        <h5>Discounted Laptops</h5>
        <h4 class="mt-8 font-josesans font-bold">GET UP TO 30% OFF TODAY ONLY</h4>
      </div>
    </div>
    <div class="lg:w-3/12 sm:w-full my-3 cursor-pointer relative">
      <div class="h-full img-container">
        <%= image_tag("hero 1.jpg", alt: "Hero 1", class: "img-banner h-100") %>
      </div>
      <div class="center-inner z-10 text-white ">
        <h5>Head Phones</h5>
        <h5 class="font-josesans font-bold mt-4">40% OFF TODAY ONLY</h5>
        <%= link_to products_url do %>
          <div class="absolute rounded-circle ml-auto -right-1/2 w-24 h-24 bg-black mt-4 flex flex-col justify-center items-center">
            <span class="material-icons text-white flip-x">north_east</span>
            <p class="text-white h6 font-josesans mt-2">Shop now</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="mbr mx-auto my-3 w-11/12">
  <h1 class="text-center my-3 f1 font-bold font-josesans">Featured Products</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-4 xl:gap-8">
    <% @products_view.each do |product_view| %>
      <%= render 'products/product_item', product: product_view %>
    <% end %>
  </div>
</section>

<%= render 'products/showcase_product' %>

<section class="mbr mx-auto my-3 w-11/12">
  <h1 class="text-center my-3 font-josesans font-bold f1">On Sale</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-4 xl:gap-8">
    <% @products_view_sale.each do |product_view| %>
      <%= render 'products/product_item_sale', product_view: product_view %>
    <% end %>
  </div>
</section>

<section class="mx-16 flex">
  <div class="flex w-6/12 shadow-md mr-3 background-light py-12 relative">
    <div class="pl-16 mt-1 z-50">
      <h5 class="font-josesans font-bold">GET UP TO 30% OFF TODAY ONLY</h5>
      <H3>THE 4K HDR SCREEN PHONE</H3>
      <%= link_to products_url do %>
        <div class="rounded-circle w-24 h-24 bg-black mt-8 flex flex-col justify-center items-center">
          <span class="material-icons text-white flip-x">north_east</span>
          <p class="text-white h6 font-josesans mt-2">Shop now</p>
        </div>
      <% end %>
    </div>
    <div class="background-light my-auto absolute right-0 bottom-0 transform -translate-y-1/8">
      <%= image_tag("phone_sss20.jpg", class: "mix-blend-darken w-9/12 h-75") %>
    </div>
  </div>

  <div class="flex w-6/12 shadow-md mr-3 background-light py-12 relative">
    <div class="pl-16 mt-1 z-50">
      <h5 class="font-josesans font-bold">GET UP TO 20% OFF TODAY ONLY</h5>
      <H3>THE 4K 128MPS CAMERA</H3>
      <%= link_to products_url do %>
        <div class="rounded-circle w-24 h-24 bg-white mt-8 flex flex-col justify-center items-center">
          <span class="material-icons">north_east</span>
          <p class="h6 font-josesans mt-2">Shop now</p>
        </div>
      <% end %>
    </div>
    <div class="background-light my-auto absolute right-0 bottom-0 transform -translate-y-1/8">
      <%= image_tag("phones.jpg", class: "mix-blend-darken w-9/12 h-75") %>
    </div>
  </div>

</section>

<section class="mbr mx-auto my-3 font-weight-lighter w-11/12">
  <h1 class="text-center my-3 font-bold font-josesans f1">Recent View</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-4 xl:gap-8">
    <% @products_view.take(6).each do |product_view| %>
      <%= render 'products/product_item', product: product_view %>
    <% end %>
  </div>
</section>

<%= render 'products/showcase_product' %>

<section class="my-24 mx-16">
  <h1 class="text-center my-3 font-bold font-josesans f1">Get Fashion News</h1>
  <div class="flex flex-cols-3 container-xl mx-auto child-px-2-not-first">
    <div class="col-lg-4 flex-cols-3 col-sm-12 col-md-6 text-center relative">
      <div class="opacity-anim h-full">
        <%= image_tag("blog post 3.jpg", alt: "Product", class: "card-img-top relative") %>
        <div class="p-4 rounded card-fashion w-3/4">
          <h4 class="my-0 title font-bold f4 font-josesans">10 Best Laptops</h4>
          <p class="sub-title">
            Top ten laptops you can choose from to meet your need
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 flex-cols-3 col-sm-12 col-md-6 text-center relative">
      <div class="opacity-anim h-full">
        <%= image_tag("blog post 2.jpg", alt: "Product", class: "card-img-top relative h-full") %>
        <div class="p-4 rounded card-fashion w-3/4">
          <h4 class="my-0 title font-bold f4 font-josesans">5 Best Macbooks</h4>
          <p class="sub-title">
            High quality, lightweight, endurable macbook for office word
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 flex-cols-3 col-sm-12 col-md-6 text-center relative">
      <div class="opacity-anim h-full">
        <%= image_tag("blog_post_1.jpg", alt: "Product", class: "card-img-top relative h-full") %>
        <div class="p-4 rounded card-fashion w-3/4">
          <h4 class="my-0 title font-bold font-josesans f4">10 Best PCs</h4>
          <p class="sub-title">
            Top ten powerful pcs for your work or entertainment -
          </p>
        </div>
      </div>
    </div>
  </div>

</section>

<section class="m-16 background-light py-16 rounded-lg shadow-md">
  <div class="w-8/12 mx-auto">
    <h5 class="text-center f5 color-gray-fade uppercase font-josesans">New letter</h5>
    <h1 class="f1 font-bold text-center font-josesans">Contact us for more sale off</h1>
    <h5 class="f5 text-center color-gray-fade">Subscribe your email and get started</h5>
    <div class="flex items-stretch w-8/12 mx-auto my-8">
      <input type="text" class="w-8/12 px-4 py-3 rounded-full font-medium bg-gray-100 border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:shadow-md focus:border-gray-400 focus:bg-white" placeholder="Enter your email here">
      <div class="w-3/12 ml-auto px-8 py-2 bg-white shadow-full rounded-full text-center f5 font-josesans color-fade cursor-pointer relative">
        <p class="center-inner color-fade">
          Subscribe
        </p>
      </div>
    </div>
  </div>

  <div class="flex justify-between w-10/12 mx-auto mt-16">
    <div class="w-3/12 text-center">
      <h3 class="f3">Find Us</h3>
      <div class="mt-4">
        <p>31028 Vazzola</p>
        <p>New York</p>
      </div>

    </div>
    <div class="w-3/12 text-center">
      <h3 class="f3">Call Us</h3>
      <p class="mt-4">+039 035 523 322</p>
      <p>company@email.com</p>
    </div>

    <div class="w-3/12 text-center">
      <h3 class="f3">About Us</h3>
      <%= link_to about_path do %>
        <div class="mx-8 mt-4">
          <div class="ml-auto px-8 py-2 bg-white shadow-full rounded-full text-center f5 font-josesans color-fade cursor-pointer relative">
            Learn More
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>