config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :shopping_cart
      post :create_order_old_info
      post :remove_product_cart_from_cart
    end
  end
  get 'cart/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'contact' => 'contact#index'
  get 'about' => 'about#index'
  root to: 'home#index'

  resources :products do
    member do
      post :add_to_cart
      post :add_to_wishlist
      post :quick_view
      post :update_form_add_to_cart
    end

    collection do
      post :save_attributes
      post :create_variations_from_attrs
      post :change_product_form
      post :add_attributes_input
      post :filter_by_price
      post :add_comment
      post :add_reply
      post :show_replies
      post :add_reply_form
      post :toggle_like
      post :add_category
    end
  end
  resources :user do
  end
  resources :comment
  resources :user, collection: {add_to_cart: :post}

  resources :cart do
    collection do
      post :modify_qty
      post :view_cart
    end
  end
  devise_for :users do
    get '/users/sign_out' => 'devise/session#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  # mount_uploaders :images, ImageUploader
  # serialize :images, JSON
  # serialize :up_sale, Array
  # serialize :cross_sale, Array
  paginates_per 9

  belongs_to :user
  has_and_belongs_to_many :categories, required: false
  has_many :product_variations, dependent: :destroy
  has_many :product_carts, as: :product
  has_many :comments, dependent: :destroy
  has_one :product_linked, through: :product_meta
  has_many :product_upsells, class_name: 'Product', through: :product_linked
  has_one :product_meta, as: :product, required: false, dependent: :destroy

  accepts_nested_attributes_for :product_meta
  accepts_nested_attributes_for :product_variations
  # accepts_nested_attributes_for :product_upsells

  def regular_price_text
    if product_variations.blank?
      format('%s', ActionController::Base.helpers.number_to_currency(product_meta.product_detail.regular_price))
    else
      prices = product_variations.map { |it| it.product_meta.product_detail.regular_price }
      format('%<low>s - %<high>s',
             { low: ActionController::Base.helpers.number_to_currency(prices.min),
               high: ActionController::Base.helpers.number_to_currency(prices.max) })
    end
  end

  def sale_price_text
    prices = product_variations.filter_map do |it|
      it.product_meta.product_sale_price&.sale_price unless it.product_meta.product_sale_price.nil?
    end.to_set
    if prices.blank?
      if product_meta.product_sale_price.nil?
        ''
      else
        ActionController::Base.helpers.number_to_currency(product_meta.product_sale_price.sale_price)
      end
      # format('%s', ActionController::Base.helpers.number_to_currency(product_meta.product_sale_price.sale_price))
    elsif prices.size == 1
      format('%s', ActionController::Base.helpers.number_to_currency(prices.first))
    else
      format('%<low>s - %<high>s',
             { low: ActionController::Base.helpers.number_to_currency(prices.min),
               high: ActionController::Base.helpers.number_to_currency(prices.max) })
    end
  end

  def price_text
    if sale_price_text.blank?
      regular_price_text
    else
      sale_price_text
    end
  end

  def price
    product_meta.product_sale_price&.sale_price || product_meta.product_detail.regular_price
  end

  def price_include_variation_min
    product_meta.product_sale_price&.sale_price || product_meta.product_detail.regular_price || product_variations.filter_map do |it|
      it.product_meta.product_sale_price&.sale_price unless it.product_meta.product_sale_price.nil?
    end.to_set.min
  end

  def price_include_variation_max
    product_meta.product_sale_price&.sale_price || product_meta.product_detail.regular_price || product_variations.filter_map do |it|
      it.product_meta.product_sale_price&.sale_price unless it.product_meta.product_sale_price.nil?
    end.to_set.max
  end

  def rating
    ratings = comments.map(&:rating)
    (ratings.sum.to_f / ratings.size).truncate(1)
  end

  def category
    categories[0]
  end

  delegate :name, :regular_price, to: :product_meta
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# noinspection ALL
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update]
  before_action :init_product_form_model, only: %i[new change_product_form]
  # before_action :fix_params, only: %i[create update]

  attr_reader :product

  # GET /products
  # GET /products.json
  def index
    @products = if params[:cat].nil?
                  Product.order(:updated_at)
                else
                  Category.find_by('name ILIKE ?', params[:cat])&.products
                end
    @num_product_found = @products&.size || 0
    @products = @products&.page(params[:page])
    @product = Product.new
    @recent_products = []
    (session[:product_recent_ids] || []).each do |id|
      @products.each do |product|
        if product.id.to_s == id
          @recent_products.push(product)
          break
        end
      end
    end
    @products_view_sale = Product
                            .joins(product_meta: [:product_sale_price])
                            .where('sale_date_start < ?', 0.day.ago)
                            .map { |product| ProductView.new(product) }
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @user = current_user
    @comment = Comment.new
    @reply = Reply.new
    @comments = @product.comments
    @product_upsells = @product.product_upsells
    @hash_attrs = helpers.attrs_of_product_variation(@product)

    session[:product_recent_ids] = ([params[:id]] + (session[:product_recent_ids] || [])).uniq
    session[:product_recent_ids].pop if session[:product_recent_ids].size > 5
  end

  # GET /products/new
  def new
    @products = Product.all
    init_product_form_model
    @categories = Category.all
    @product_attr = ProductAttributesName.new
    gon.product_names = @products.map(&:name)
    gon.product_ids = @products.map(&:id)

    session[:product] = @product
    session.delete(:product_type)
    session.delete(:num_form_variation)
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
    meta = @product.product_meta
    meta.product_shipping = ProductShipping.new if meta.product_shipping.nil?
    meta.product_linked = ProductLinked.new if meta.product_linked.nil?

    variations = @product.product_variations
    unless variations.empty?
      # params to pass to form
      @product_type = 'variation'
      @active = 4
      @expand = false
      @num_form_variation = variations.size

      # Variations
      @product_attrs = ProductAttributesName.all
      merge = helpers.products_cartesian(@product_attrs)
      @attrs_list_values = merge[:value]
      @attrs_list_values = @attrs_list_values.map do |attrs_values|
        attrs_values.map do |value|
          ProductAttributesValue.where(value: value).first
        end
      end

      @num_form_variation.times do
        variation = @product.product_variations.blank? ? @product.product_variations.build : @product.product_variations[0]
        variation_meta = variation.product_meta.nil? ? variation.build_product_meta : variation.product_meta
        variation_meta.build_product_detail if variation_meta.product_detail.nil?
        variation_meta.build_product_inventory if variation_meta.product_inventory.nil?
        variation_meta.build_product_shipping if variation_meta.product_shipping.nil?
        variation_meta.build_product_sale_price if variation_meta.product_sale_price.nil?

        @attrs_list_values[0].length.times do
          variation.product_attributes_values.build
        end
      end
    end
  end

  # POST /products
  # POST /products.json
  def create
    puts params
    @categories = Category.all
    # Build New Category here

    # Modify params before build product to have affect
    upsell_ids_string = params[:product][:product_meta_attributes][:product_linked_attributes][:product_upsell_ids_string]
    cross_sell_ids_string = params[:product][:product_meta_attributes][:product_linked_attributes][:product_cross_sell_ids_string]

    upsell_ids = []
    upsell_ids_string&.split(',')&.each do |upsell_id|
      upsell_ids << upsell_id.to_i
    end

    params[:product][:product_meta_attributes][:product_linked_attributes][:product_upsell_ids] = upsell_ids

    cross_sell_ids = []
    cross_sell_ids_string&.split(',')&.each do |cross_sell_id|
      cross_sell_ids << cross_sell_id.to_i
    end

    params[:product][:product_meta_attributes][:product_linked_attributes][:product_cross_sell_ids] = cross_sell_ids

    @product = current_user.products.build(product_params)
    # merge time and date into timestamp
    sale_price = @product.product_meta.product_sale_price
    if !sale_price.nil? && !sale_price.sale_date_start.nil? && !sale_price.sale_date_start.nil?
      time_start = Time.zone.parse(sale_price.sale_date_start_time)
      sale_price.sale_date_start = Time.zone.parse("#{sale_price.sale_date_start.strftime('%F')} #{time_start&.strftime('%T')}")

      time_end = Time.zone.parse(sale_price.sale_date_end_time || '00:00')
      sale_price.sale_date_end = Time.zone.parse("#{sale_price.sale_date_start.strftime('%F')} #{time_end&.strftime('%T')}")
    end

    unless @product.product_variations.blank?
      @product.product_variations.each do |variation|
        sale_price = variation.product_meta.product_sale_price
        next if sale_price.nil? || sale_price.sale_date_start.nil? || sale_price.sale_date_end.nil?

        time_start = Time.zone.parse(sale_price.sale_date_start_time.presence || '00:00')
        sale_price.sale_date_start = Time.zone.parse("#{sale_price.sale_date_start.strftime('%F')} #{time_start.strftime('%T')}")

        time_end = Time.zone.parse(sale_price.sale_date_end_time.presence || '00:00')
        sale_price.sale_date_end = Time.zone.parse("#{sale_price.sale_date_end.strftime('%F')} #{time_end.strftime('%T')}")
      end
    end

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        session.delete(:product)
      else
        # Init form model to enable re submit
        init_product_form_model
        format.html { render :new, notice: 'Error has been occured.' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        # Setup variation if error form is variation product
        if session[:product_type] == 'variation'
          # params to pass to form
          @product_type = session[:product_type]
          @active = 4
          @expand = true
          @num_form_variation = session[:num_form_variation]

          # Variations
          @product_attrs = ProductAttributesName.all
          merge = helpers.products_cartesian(@product_attrs)
          @attrs_list_values = merge[:value]
          @attrs_list_values = @attrs_list_values.map do |attrs_values|
            attrs_values.map do |value|
              ProductAttributesValue.where(value: value).first
            end
          end

          @num_form_variation.times do
            variation = @product.product_variations.blank? ? @product.product_variations.build : @product.product_variations[0]
            variation_meta = variation.product_meta.nil? ? variation.build_product_meta : variation.product_meta
            variation_meta.build_product_detail if variation_meta.product_detail.nil?
            variation_meta.build_product_inventory if variation_meta.product_inventory.nil?
            variation_meta.build_product_shipping if variation_meta.product_shipping.nil?
            variation_meta.build_product_sale_price if variation_meta.product_sale_price.nil?

            @attrs_list_values[0].length.times do
              variation.product_attributes_values.build
            end
          end

        end
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # post /products/add_category
  # @param category_name
  def add_category
    category_name = params[:category_name]
    @new_category = current_user.categories.build(name: category_name) unless category_name.nil? || category_name.blank?

    respond_to do |format|
      if @new_category.save
        format.js { render 'products/response_add_category', locals: { success: true } }
      else
        format.js { render 'products/response_add_category', locals: { success: false } }
      end
    end
  end

  # @return [FalseClass]
  def add_to_cart
    # Find cart if has any
    @cart = Cart.find_by(user_id: current_user.id)
    # If not build one
    if @cart.nil?
      @cart = current_user.build_cart
      return false unless @cart.save
    end

    # Find product cart already in cart for update quantity if user add again
    product_for_cart = Product.find_by(id: product_cart_params['product_id']) || ProductVariation.find_by(id: product_cart_params['product_id'])
    # product_cart = ProductCart.find_by(product_id: product_cart_params['product_id'])
    product_cart = @cart.product_carts.where(product_id: product_cart_params['product_id']).first
    # If not have then add new one
    # Othewise add it quantity to 1 or quantity if have
    if product_cart.nil?

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  #  Compute the cartesian set product
  # @param attrs: an array
  # @param arr_attrs: an array of array to compute cartesian product
  def cartesian(attrs, arr_attrs)
    merge = []
    attrs.each do |attr1|
      arr_attrs[0].each do |attr2|
        merge.push([*attr1, attr2])
      end
    end
    return cartesian(merge, arr_attrs[1..]) if arr_attrs.length > 1

    merge
  end

  # @param attrs_values: values for first element
  # @param product_attrs: remain element for calling recursive
  # noinspection MissingYardReturnTag
  def product_cartesian(attrs_values, product_attrs)
    merge = {value: [], attrs_list_values: []}
    # loop through all values consecutive elements to build cartesian product for those two elements
    # NOTE: for first time value1 will be just value but when call recursive it is array (of all value so far)
    attrs_values.each do |value1|
      product_attrs[0][:value].split('|').each do |value2|
        # push all values (need to decompose value1 - it can be array) - see ruby array decompose
        merge[:value].push([*value1, value2])
      end
    end
    # save attrs for using in views
    merge[:attrs_list_values].push(*attrs_values)
    # recursive call for remaining
    return product_cartesian(merge[:value], product_attrs[1..]) if product_attrs.length > 1

    # push last attrs to complete all attrs
    merge[:attrs_list_values].push(product_attrs[0][:value].split('|'))
    merge
  end

  def products_cartesian(product_attrs)
    return product_attrs[0].value.split('|') if product_attrs.length == 1

    product_cartesian(product_attrs[0][:value].split('|'), product_attrs[1..])
  end

  # Get all set of attr_name: [attr_value] for product that have product_variations
  def attrs_of_product_variation(product)
    hash_attrs = {}
    product.product_variations.each do |v|
      v.product_attributes_values.each do |attr|
        name = attr.product_attributes_name.name.downcase
        hash_attrs[name] = if hash_attrs.key?(name)
                             hash_attrs[name].add(attr.value.downcase)
                           else
                             Set[attr.value.downcase]
                           end
      end
    end
    hash_attrs
  end

  def attr_values_nocase_variation(product_variation)
    product_variation.product_attributes_values.map { |it| it.value.downcase }
  end
end

app/views/products/_input_attributes.html.erb
<div class="flex flex-grow w-full my-8 form-add-attributes">
  <div class="control w-4/12 mt-2">
    <div>
      <label class="text optional label text-left p-0 flex" for="product-attribute-name">Name</label>
      <textarea class="product-attributes-name text optional input flex flex-grow w-full py-2 rounded-lg font-medium bg placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white placeholder-gray-800" name="product_attribute[name]" id="product-attribute-name" placeholder="Name"></textarea>

      <%#= form_save_attr.input :name, multiple: true, label: "Name", required: false,
                                                           input_html: {class: "input flex flex-grow w-full py-2 rounded-lg font-medium bg placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white placeholder-gray-800"}, wrapper: false, label_html: {class: "label text-left p-0 flex"} %>

      <!-- Attrs Visible -->
      <div class="flex justify-start items-center mt-3">
        <label class="flex justify-center items-center m-0">
          <input type="checkbox" name="use_paypal">
          <span class="inline-block rounded-circle icon-size checkbox-size border-color-default border-1 checkbox-span mr-2"></span>
        </label>
        <span class="f7">Visible on product page</span>
      </div>
      <!-- !Attrs Visible -->

      <!-- Used for variations products -->
      <div class="flex justify-start items-center mt-3">
        <label class="flex justify-center items-center m-0">
          <input type="checkbox" name="use_paypal">
          <span class="inline-block rounded-circle icon-size checkbox-size border-color-default border-1 checkbox-span mr-2"></span>
        </label>
        <span class="f7">Used for variations</span>
      </div>
      <!-- !Used for variations products -->
    </div>

  </div>
  <div class="control flex-grow ml-1 mt-2 flex flex-col justify-start">
    <%#= form_save_attr.input :value, multiple: true, label: "Value (separate by |)", required: false, :as => :text,
                                                         input_html: {class: "input flex flex-grow w-full py-2 rounded-lg font-medium bg placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white placeholder-gray-800"}, wrapper: false, label_html: {class: "label text-left p-0 flex"} %>

    <label class="text optional label text-left p-0 flex" for="product-attribute-value">Value
      (separate by |)</label>
    <textarea placeholder="Value1|Value2|..." class="product-attributes-value text optional input flex flex-grow w-full py-2 rounded-lg font-medium bg placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white placeholder-gray-800" name="product_attribute[value]" id="product-attribute-value"></textarea>
  </div>

</div>

app/views/products/_product_images_carousel.html.erb
<div class="carousel relative rounded relative overflow-hidden pr-4">
  <div class="carousel-inner relative overflow-hidden w-full bg-product-img">

    <% if product.product_variations.blank? %>
      <% size = product.product_meta.images.size %>
      <% product.product_meta.images.each_with_index do |image, index| %>
        <input class="carousel-open" type="radio" id="carousel-<%= index + 1 %>" name="carousel" aria-hidden="true" hidden="" <%= 'checked=checked' if index == 0 %>>
        <div class="carousel-item absolute opacity-0" style="height: 500px;">
          <%= image_tag(image.url, alt: "Product", class: "img-fluid center-inner w-full h-100 max-h-100 object-contain mix-blend-darken") %>
        </div>
        <label for="carousel-<%= index + 1 - 1 < 1 ? size : index + 1 - 1 %>"
               class="control-<%= index + 1 %> w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto"><i
          class="fas fa-angle-left mt-3"></i></label>
        <label for="carousel-<%= index + 1 + 1 > size ? 1 : index + 1 + 1 %>"
               class="next control-<%= index + 1 %> w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto"><i
          class="fas fa-angle-right mt-3"></i></label>

      <% end %>
    <% else %>
      <% size = product.product_variations.size %>
      <% product.product_variations.each_with_index do |variation, index| %>
        <input class="carousel-open" type="radio" id="carousel-<%= index + 1 %>" name="carousel" aria-hidden="true" hidden="" <%= 'checked=checked' if index == 0 %>>
        <div class="carousel-item absolute" style="height: 500px;">
          <div class="block h-full w-full">
            <%= image_tag(variation.product_meta.images[0].url, alt: "Product", class: "img-fluid center-inner w-full h-100 object-contain mix-blend-darken") %>
          </div>
        </div>
        <label for="carousel-<%= index + 1 - 1 < 1 ? size : index + 1 - 1 %>"
               class="control-<%= index + 1 %> w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto"><i
          class="fas fa-angle-left mt-3"></i></label>
        <label for="carousel-<%= index + 1 + 1 > size ? 1 : index + 1 + 1 %>"
               class="next control-<%= index + 1 %> w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto"><i
          class="fas fa-angle-right mt-3"></i></label>
      <% end %>
    <% end %>


    <!-- Add additional indicators for each slide-->
    <ol class="carousel-indicators">
      <% (size || 1).times do |i| %>
        <li class="inline-block mr-3">
          <label for="carousel-<%= i + 1 %>"
                 class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
        </li>
      <% end %>
    </ol>

  </div>
</div>

app/views/products/_product_item.html.erb
<% col ||= 3 %>
<% sort ||= false %>
<div class="text-center cursor-pointer product-card <%= "grid-sort-#{col}" if sort %>">
  <div class="grid-sizer lg:w-3"></div>
  <div class="card opacity-anim overflow-hidden">
    <div class="bg-product-img py-8">
      <%= link_to product_path(product.id) do %>
        <%= image_tag(product_first_img(product), alt: "Product", class: "mix-blend-darken transform image-product-item-height hover:scale-105 w-full duration-500 object-contain") %>
      <% end %>
    </div>
    <div class="px-2 mx-1 mt-2">
      <% if product.category %>
        <p class="my-0 sub-title hover:color-hover transform hover:scale-105 duration-200 opacity-50"><%= product.category.name %></p>
      <% end %>
      <p class="my-0 title hover:color-hover transform hover:scale-105 duration-200 product-name"><%= product.product_meta.product_detail.name %></p>
      <div class="rating text-warning font-size-14">
        <span><i class="fas fa-star"></i></span>
        <span><i class="fas fa-star"></i></span>
        <span><i class="fas fa-star"></i></span>
        <span><i class="fas fa-star"></i></span>
        <span><i class="fas fa-star"></i></span>
      </div>
      <p class="font-bold hover:color-hover transform hover:scale-105 duration-200 font-fredoka f4 my-0 product-price"><%= product.price_text %></p>
      <form action="<%= quick_view_product_path(id: product.id, product_id: product.id) %>" data-remote="true" method="post">
        <button type="submit" class="flex justify-center button-wishlist px-4 py-2 my-3 mx-auto font-roboto outline-none-imp font-bold items-center duration-500">
          <i class="fa fa-heart mr-2 duration-500"></i>Add to Cart
        </button>
      </form>

    </div>
  </div>
</div>

app/views/products/_product_item_sale.html.erb
<div class="text-center mb-5">
  <div class="text-center cursor-pointer product-card relative">
    <div class="card opacity-anim overflow-hidden">
      <div class="bg-product-img py-8">
        <%= link_to product_path(product_view.product) do %>
          <%= image_tag(product_first_img(product_view.product), alt: "Product", class: "mix-blend-darken transform w-full image-product-item-height hover:scale-105 duration-500 object-contain") %>
        <% end %>
      </div>

      <div class="absolute left-1 top-1 w-16 h-16 rounded-circle bg-gray-800 text-white py-3 px-2 f5 font-extrabold font-roboto">
        <p class="center-inner">
          <%= p product_view.sale_off %>
        </p>
      </div>
      <div class="px-3 mx-1 mt-2">
        <% unless product_view.category.nil? %>
          <p class="my-0 sub-title text-gray-300 opacity-50 hover:color-hover transform hover:scale-105 duration-200"><%= product_view.category.name %></p>
        <% end %>
        <p class="my-0 title hover:color-hover transform hover:scale-105 duration-200"><%= product_view.name %></p>
        <div class="rating text-warning font-size-14">
          <span><i class="fas fa-star"></i></span>
          <span><i class="fas fa-star"></i></span>
          <span><i class="fas fa-star"></i></span>
          <span><i class="fas fa-star"></i></span>
          <span><i class="fas fa-star"></i></span>
        </div>
        <div class="flex justify-center">
          <h6 class="font-baloo f2"><%= number_to_currency(product_view.product_meta.sale_price) %></h6>
          <h6 class="font-baloo ml-3 f3 flex justify-center flex-col">
            <del><%= number_to_currency(product_view.product_meta.product_detail.regular_price) %></del>
          </h6>
        </div>
        <!--              <p class="font-bold hover:color-hover transform hover:scale-105 duration-200 font-fredoka f4 my-0"><%#= product.product_meta.product_detail.regular_price %> $</p>-->
        <!--              <div class="custom-btn mx-3 font-fredoka my-2">Add To Cart</div>-->
        <form action="<%= quick_view_product_path(id: product_view.id, product_id: product_view.id) %>" data-remote="true" method="post">
          <button type="submit" class="flex justify-center button-wishlist px-4 py-2 my-3 mx-auto font-roboto outline-none-imp font-bold items-center duration-500">
            <i class="fa fa-heart mr-2 duration-500"></i>Add to Cart
          </button>
        </form>
      </div>
    </div>
  </div>

</div>

app/views/products/_product_item_simple.html.erb
<% col ||= 3 %>
<% sort ||= false %>
<div class="text-center cursor-pointer product-card <%= "grid-sort-#{col}" if sort %>">
  <div class="grid-sizer lg:w-3"></div>
  <div class="card opacity-anim overflow-hidden bg-product-img">
    <%= link_to product_path(product) do %>
      <%= image_tag(product_first_img(product), alt: "Product", class: "mix-blend-darken transform image-product-item-height hover:scale-105 w-full duration-500 object-contain") %>
    <% end %>
    <div class="px-2 mx-1 mt-2">
      <p class="my-3 f4 title hover:color-hover transform hover:scale-105 duration-200 product-name"><%= product.product_meta.product_detail.name %></p>
      <p class="my-3 font-bold hover:color-hover transform hover:scale-105 duration-200 font-fredoka f4 my-0 product-price"><%= product.price_text %></p>
      <form action="<%= quick_view_product_path(id: product.id, product_id: product.id) %>" data-remote="true" method="post" class="duration-500 transition-all max-h-0 hover:height">
        <button type="submit" class="flex justify-center button-wishlist px-4 py-2 my-3 mx-auto font-roboto outline-none-imp font-bold items-center duration-500">
          <i class="fa fa-heart mr-2 duration-500"></i>Add to Cart
        </button>
      </form>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="background-white-grey py-8">
  <section class="rounded-md background-white-grey border shadow-md m-4 pb-4 overflow-hidden">
    <div class="font-josesans font-bold bg-white flex items-center relative border-b px-4 mb-4">
      <%= link_to :back do %>
        <div class="flex items-baseline py-3 pr-4 cursor-pointer border-r">
          <i class="fas fa-arrow-left mr-2"></i>Back
        </div>
      <% end %>
      <div class="mx-8">
        Edit Product
      </div>
    </div>
    <%= render 'form', product: @product %>
  </section>
</div>

app/views/products/response_add_reply.js.erb
<% if success %>
toastr.success("Success add reply!")
$("#reply-container-<%= @reply.comment.id %>").append("<%= escape_javascript render 'reply/reply_item', reply: @reply %>")
$("#reply-form-<%= @reply.comment.id %>").remove()
<% else %>
toastr.error("Error when adding comment! Please try again.")
<% end %>

app/views/products/response_filter_products.js.erb
$("#container-product-grid-items-product-index").html("<%= escape_javascript render 'product_grid_items_sortable', products: @products_filtered %>")